### ISSUE TITLE
Plugin overrides new user settings and will not take user to /pay/ page

### ISSUE THREAD

**Issue by ghost** [intelliants/subrion-plugin-paypal#3]
New user setting does not require email confirmation before login but paypal plugin overrides that and leads user to 403 Access denied page. URL is cms/pay/someuniquekey and user cannot pay or login and pay.

**Comment by 4unkur** [comment]
Hello @hippybear, 

This issue is not related to the plugin, this bug is in the core.
It was fixed but not released yet. Please see https://github.com/intelliants/subrion/issues/121

Thanks.
